version: '3.9'
services:
  app:
    image: phinixhq/ethereum-fullnode-exporter
    restart: unless-stopped
    environment: 
      REFRESH_INTERVAL_MILLISECONDS: "60000"
      FULLNODE_BASE_URL:
      GLOBAL_BLOCKBOOK_ENDPOINT:
      COIN_NAME:
    ports:
      - "9099:9099"
